spring:
  profiles: local
#  datasource:
#    url: ENC() 
#    username: ENC(EY+HCJzLmq/i7ufUACFryw==)
#    password: ENC(C0FAyNzGoGyfkiJlImCckw==)
  
server:
  port: 9999
  
  
jwt:
  expmin: 5
  salt: MYSALT

